import { IFormInput } from "@/components/Custom/FormComponents/FormInput";
import countries from "./countries.json";
const inputs: { [key: string]: IFormInput[] } = {
  login: [
    {
      id: "1",
      name: "email",
      type: "text",
      placeholder: "Email",
      label: "Email",
      required: true,
      pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$",
    },
    {
      id: "2",
      name: "password",
      type: "password",
      placeholder: "Password",
      label: "Password",
      required: true,
      pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\\W)(?!.* ).{8,16}$",
    },
  ],
  resetPass: [
    {
      id: "1",
      name: "email",
      type: "text",
      placeholder: "Email",
      label: "Email",
      helperText: "Invalid Email",
      required: true,
      pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$",
    },
  ],
  signup: [
    {
      id: "1",
      name: "email",
      type: "text",
      placeholder: "Email",
      label: "Email",
      helperText: "Invalid Email",
      required: true,
      pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$",
    },
    {
      id: "2",
      name: "password",
      type: "password",
      placeholder: "Password",
      label: "Password",
      helperText:
        "Passwords should be 8-20 characters and include atleast 1 letter, 1 number and 1 special character",
      required: true,
      pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\\W)(?!.* ).{8,16}$",
    },
    {
      id: "3",
      name: "confirmPassword",
      type: "password",
      placeholder: "Confirm Password",
      label: "Confirm Password",
      helperText:
        "Passwords should be 8-20 characters and include atleast 1 letter, 1 number and 1 special character",
      required: true,
      pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\\W)(?!.* ).{8,16}$",
    },
  ],
  billingInfo: [
    {
      id: "firstName",
      name: "firstName",
      label: "First Name",
      type: "text",
      placeholder: "First Name",
      required: true,
    },
    {
      id: "lastName",
      name: "lastName",
      label: "Last Name",

      type: "text",
      placeholder: "Last Name",
      required: true,
    },
    {
      id: "email",
      name: "email",
      type: "email",
      label: "Billing Email",
      placeholder: "Billing Email",
      helperText: "Invalid email",
      pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$",
      required: true,
    },
    {
      id: "whatsappNumber",
      name: "whatsappNumber",
      type: "tel",
      label: "WhatsApp Number",
      placeholder: "WhatsApp Number",
      required: true,
      helperText: "Not a telephone number",
    },
    {
      id: "address1",
      name: "address1",
      type: "text",
      label: "Address Line 1",
      placeholder: "Address Line 1",
      required: true,
    },
    {
      id: "address2",
      name: "address2",
      type: "text",
      label: "Address Line 2",
      placeholder: "Address Line 2",
    },
    {
      id: "country",
      name: "country",
      options: countries,
      type: "text",
      label: "Country",
      placeholder: "Country",
      required: true,
    },
    {
      id: "city",
      name: "city",
      type: "text",
      label: "City",
      placeholder: "City",
    },
    {
      id: "postalCode",
      name: "postalCode",
      type: "text",
      label: "Postal Code",
      placeholder: "Postal Code",
      required: true,
    },
  ],
};

export default inputs;
