import Product from "../interfaces/Products";

const mockProducts: Product[] = [
  {
    id: "1",
    name: "Air Jordan 1 High Retro",
    defaultPrice: 190,
    mainImage: "products/u0ebhsb9dsd2fjzdh2f1",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "2",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 250,
    mainImage: "products/in010fkjxbdcmwmbsxhk",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "3",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 320,
    mainImage: "products/kmm7sjx17czvdqyu6sfs",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "4",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 180,
    mainImage: "products/j9wwgzgv3erpk26rdniz",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "5",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 160,
    mainImage: "products/qx7kghsosy9gq08pczf9",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "6",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 3250,
    mainImage: "products/yx3xpow3narimw4qsjvi",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "7",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 650,
    mainImage: "products/w69cfuvhcijsvpcopo3g",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "8",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 185,
    mainImage: "products/h5bqo0txnk67arsnkcoj",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "9",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 197,
    mainImage: "products/p5kj00yujdyki5qx0tfl",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "10",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 276,
    mainImage: "products/u3m4bqr1boqcofi1tmp8",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "11",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 435,
    mainImage: "products/n2siwivisv33vzqfd3g6",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "12",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 186,
    mainImage: "products/vbhd5z6n4qvtpiuohqmr",
    variants: [
      { name: "high", price: 350 },
      { name: "normal", price: 450 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
];

export default mockProducts;
