import Product from "../interfaces/Products";
import mockReviews from "./mockReviews";

const mockProducts: Product[] = [
  {
    id: "1",
    name: "Air Jordan 1 High Retro",
    desc: "Duis non libero sodales, blandit mi ac, hendrerit dolor. Fusce ut diam ligula. Donec eu quam non quam tristique fermentum in nec leo. In dapibus justo ut finibus facilisis. Nunc pulvinar blandit enim sed vestibulum. Sed commodo tellus ut massa fermentum, id fringilla justo elementum. Sed ut molestie nunc, condimentum gravida ex.",
    defaultPrice: 190,
    mainImage: "products/u0ebhsb9dsd2fjzdh2f1",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
    images: [
      "products/in010fkjxbdcmwmbsxhk",
      "products/j9wwgzgv3erpk26rdniz",
      "products/qx7kghsosy9gq08pczf9",
      "products/w69cfuvhcijsvpcopo3g",
    ],
    reviews: mockReviews,
  },
  {
    id: "2",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 250,
    mainImage: "products/in010fkjxbdcmwmbsxhk",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: "blue",
    availability: "available",
  },
  {
    id: "3",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 320,
    mainImage: "products/kmm7sjx17czvdqyu6sfs",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "4",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 180,
    mainImage: "products/j9wwgzgv3erpk26rdniz",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "5",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 160,
    mainImage: "products/qx7kghsosy9gq08pczf9",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "6",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 3250,
    mainImage: "products/yx3xpow3narimw4qsjvi",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "7",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 650,
    mainImage: "products/w69cfuvhcijsvpcopo3g",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "8",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 185,
    mainImage: "products/h5bqo0txnk67arsnkcoj",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "9",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 197,
    mainImage: "products/p5kj00yujdyki5qx0tfl",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
  {
    id: "10",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 276,
    mainImage: "products/u3m4bqr1boqcofi1tmp8",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "11",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 435,
    mainImage: "products/n2siwivisv33vzqfd3g6",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "available",
  },
  {
    id: "12",
    name: "Air Jordan 2 High Retro",
    defaultPrice: 186,
    mainImage: "products/vbhd5z6n4qvtpiuohqmr",
    variants: [
      { name: "normal", price: 450 },
      { name: "high", price: 550 },
      { name: "master", price: 750 },
    ],
    colors: ["black", "red", "white", "blue"],
    availability: "out of stock",
  },
];

export default mockProducts;
